import {readFile,mkdir,writeFile,cp,rm} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {join} from 'node:path';
import {validate,safeUrl,teams} from '../assets/schema.mjs';
const root=fileURLToPath(new URL('../',import.meta.url));
const c=validate(JSON.parse(await readFile(join(root,'data/content.json'),'utf8'))),p=c.profile;
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paragraphs=text=>text.split(/\n\s*\n/).filter(Boolean).map(p=>`<p class="preserve-lines">${e(p)}</p>`).join('');
function path(value,base){const url=safeUrl(value);return /^https?:/.test(url)?url:base+url.replace(/^\//,'');}
function link(url,text,base=''){return url?`<a href="${e(path(url,base))}"${/^https?:/.test(url)?' target="_blank" rel="noopener noreferrer"':''}>${e(text)}</a>`:e(text);}
function header(base,group=false){return `<a class="skip" href="#main">Skip to content</a><header><div class="nav-wrap"><a class="wordmark" href="${base}index.html">${e(p.shortName)}<span>${e(p.institution)}</span></a><nav aria-label="Main navigation"><a href="${base}index.html#about">About</a><a href="${base}index.html#research">Research</a><a href="${base}index.html#publications">Publications</a><a href="${base}group.html"${group?' aria-current="page"':''}>Group</a><a href="${base}index.html#background">Background</a><a href="${base}index.html#contact">Contact</a></nav></div></header>`;}
function footer(base){return `<footer class="wrap"><span>© ${new Date().getFullYear()} ${e(p.name.replace('Dr. ',''))}</span><div><a href="${base}admin/">Admin</a> · <a href="#main">Back to top ↑</a></div></footer>`;}
function page(title,body,base=''){return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title>${e(title)}</title><meta name="description" content="${e(p.intro)}"><link rel="icon" href="${base}assets/favicon.svg"><link rel="stylesheet" href="${base}assets/style.css"></head><body>${body}</body></html>`;}
function section(id,index,title,body){return `<section class="section" id="${id}"><div class="section-label"><span class="index">${index}</span><h2>${e(title)}</h2></div><div class="section-body">${body}</div></section>`;}
const home=page(`${p.name} | ${p.institution}`,header('')+`<main id="main"><section class="intro wrap" id="about"><div class="intro-copy"><p class="eyebrow">${e(p.department)}</p><h1>${e(p.name)}<span class="period">.</span></h1><p class="role">${e(p.role)} <span>/</span> ${e(p.institution)}</p><p class="lead">${e(p.intro)}</p><div class="profile-links"><a class="primary" href="mailto:${e(p.email)}">Get in touch ↗</a>${link(p.orcidUrl,'ORCID ↗')}${link(p.scholarUrl,'Google Scholar ↗')}</div></div><aside class="profile-aside">${p.portrait?`<div class="portrait-slot"><img src="${e(path(p.portrait,''))}" alt="${e(p.name)}" width="1280" height="1062"></div>`:''}<p class="place">${e(p.location)}</p>${link(p.universityUrl,'University profile ↗')}</aside></section><div class="wrap">`+
section('biography','01','About',paragraphs(c.about.text))+
section('research','02','Research',`<div class="research-grid">${c.research.map(r=>`<article><span class="small-label">${e(r.label)}</span><h3>${e(r.title)}</h3><p>${e(r.description)}</p></article>`).join('')}</div>${c.grant.title?`<div class="grant"><span class="small-label">${e(c.grant.label)}</span><h3>${e(c.grant.title)}</h3><p>${e(c.grant.funder)}</p><p>${e(c.grant.description)}</p></div>`:''}`)+
section('publications','03','Selected publications',`<ol class="papers">${c.publications.map(r=>`<li><span class="year">${e(r.year)}</span><div><h3>${link(r.url,r.title+' ↗')}</h3><p>${e(r.authors)}</p><p class="journal">${e(r.journal)}</p></div></li>`).join('')}</ol>${c.book.title?`<article class="book"><span class="small-label">${e(c.book.label)}</span><h3>${e(c.book.title)}</h3><p>${e(c.book.authors)}</p><p class="book-note">${e(c.book.note)}</p>${link(c.book.url,'View book ↗')}</article>`:''}<p class="publication-source">${link(c.publicationLinks.listUrl,'Full publication list ↗')} · ${link(p.orcidUrl,'ORCID ↗')}</p>`)+
section('background','04','Academic background',`<div class="education">${c.education.map(r=>`<article><span class="year">${e(r.year)}</span><div><h3>${e(r.degree)}</h3><p>${e(r.institution)}</p><p class="secondary">${e(r.note)}</p></div></article>`).join('')}</div><div class="fellowship"><h3>${e(c.fellowship.title)}</h3><p>${e(c.fellowship.description)}</p></div>`)+
section('group','05','Research group',`<h3>${e(c.group.title)}</h3><div class="home-group-description">${paragraphs(c.group.description)}</div><div class="team-shortcuts"><a href="group.html#phd">PhD scholars</a><a href="group.html#masters">Master’s students</a><a href="group.html#jrf">JRFs</a></div><p class="group-link"><a href="group.html">View the group →</a></p>`)+
section('contact','06','Contact',`<h3>${e(c.contact.heading)}</h3><a class="email" href="mailto:${e(p.email)}">${e(p.email)} ↗</a><p class="preserve-lines">${e(c.contact.address)}</p><div class="contact-links">${link(p.orcidUrl,'ORCID ↗')}${link(c.contact.googleSiteUrl,'Google Site ↗')}</div>`)+`</div></main>`+footer(''));
const group=page(`${c.group.title} | Research group`,header('../',true)+`<main id="main" class="wrap"><div class="page-heading"><p class="eyebrow">RESEARCH GROUP · ${e(p.institution)}</p><h1>${e(c.group.title)}</h1><div class="group-intro">${paragraphs(c.group.description)}</div><nav class="team-shortcuts" aria-label="Team sections"><a href="#phd">PhD scholars</a><a href="#masters">Master’s students</a><a href="#jrf">JRFs</a></nav></div>`+teams.map(([category,title,id])=>{const members=c.members.filter(m=>m.category===category);if(!members.length&&['Project students','Alumni'].includes(category))return '';return `<section class="group-section" id="${id}"><h2>${e(title)}</h2>${members.length?`<div class="member-grid">${members.map(m=>`<article class="member">${m.photo?`<img src="${e(path(m.photo,'../'))}" alt="${e(m.name)}" width="144" height="164">`:''}<div><h3>${e(m.name)}</h3><p class="member-role">${e(m.role)}</p><p class="preserve-lines">${e(m.research)}</p><div class="member-links">${m.email?`<a href="mailto:${e(m.email)}">Email</a>`:''}${m.link?link(m.link,'Profile ↗','../'):''}</div></div></article>`).join('')}</div>`:'<div class="team-empty"><p>Member details will be added here.</p></div>'}</section>`;}).join('')+`<section class="group-enquiries"><h2>Research enquiries</h2>${paragraphs(c.group.enquiries)}<a href="mailto:${e(p.email)}">${e(p.email)}</a></section></main>`+footer('../'),'../');
await mkdir(join(root,'group'),{recursive:true});await writeFile(join(root,'index.html'),home);await writeFile(join(root,'group/index.html'),group);await writeFile(join(root,'group.html'),group.replace(/(href|src)="\.\.\//g,'$1="'));
const output=join(root,'_site');await rm(output,{recursive:true,force:true});await mkdir(output,{recursive:true});for(const name of ['index.html','group.html','group','admin','assets','data','site.config.json'])await cp(join(root,name),join(output,name),{recursive:true});await writeFile(join(output,'.nojekyll'),'');try{await cp(join(root,'CNAME'),join(output,'CNAME'));}catch(error){if(error.code!=='ENOENT')throw error;}console.log('Built homepage, group page and admin editor in _site/.');
